### ISSUE TITLE
Crashes & why is OpenCV used?

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [Rajchowdhury420/Youtube-Live-Subs-Counter#1]
I tried running your demo but it crashes when I try any user, including the supplied demo user account: UCXgGY0wkgOzynnHvSEVmE3A

This is the crash data
```
C:\Python\Anaconda3\python.exe E:/DownloadsE/livesubs.py
Traceback (most recent call last):
  File "E:/DownloadsE/livesubs.py", line 17, in <module>
    img_data = rq.get(url['href']).content
TypeError: 'NoneType' object is not subscriptable

Process finished with exit code 1
```

Why are you using OpenCV?

If it is so that you can display an image, that's easily done using PySimpleGUI.  

Oh, and your window to get the subscriber can be simplified to:
```python
username = sg.PopupGetText('Username', title='Youtube Live Sub Count')
```

This line of code displays this window:

![image](https://user-images.githubusercontent.com/13696193/62808790-2136ab80-bac7-11e9-91ad-6c8a5fe9bdbd.png)

It returns the value entered, or `None` if the user pressed Cancel or closes the window.

You're on the right track!  Headed in the right direction.  PySimpleGUI will do I think all the stuff you're trying to do without the need for OpenCV.

The documentation has just been significantly upgraded and all of the elements and functions have docstrings, making coding in PyCharm a breeze!

Thanks for giving PySimpleGUI a try!

**Comment by RajChowdhury240** [comment]
//
